name: Run Discord Bot

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: "0 * * * 1-5"  # تشغيل كل ساعة من الاثنين إلى الجمعة

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip
          python -m pip install --upgrade pip
          pip install discord.py requests beautifulsoup4 selenium

      - name: Download and install Google Chrome for Testing (v134.0.6998.88)
        run: |
          wget https://storage.googleapis.com/chrome-for-testing-public/134.0.6998.88/linux64/chrome-linux64.zip
          unzip chrome-linux64.zip -d chrome_temp
          # البنية تكون عادة: chrome_temp/chrome-linux64/chrome-wrapper + chrome
          ls -R chrome_temp
          sudo mv chrome_temp/chrome-linux64/chrome /usr/local/bin/google-chrome
          sudo chmod +x /usr/local/bin/google-chrome
          # (اختياري) قد تحتاج نقل ملف chrome-wrapper إذا أردت استخدامه
          # sudo mv chrome_temp/chrome-linux64/chrome-wrapper /usr/local/bin/
          # sudo chmod +x /usr/local/bin/chrome-wrapper
          rm -rf chrome_temp chrome-linux64.zip
          echo "Installed Chrome version:"
          /usr/local/bin/google-chrome --version

      - name: Download and install ChromeDriver for Testing (v134.0.6998.88)
        run: |
          wget https://storage.googleapis.com/chrome-for-testing-public/134.0.6998.88/linux64/chromedriver-linux64.zip
          unzip chromedriver-linux64.zip -d chromedriver_temp
          # قد تجد الملف التنفيذي في chromedriver_temp/chromedriver-linux64/chromedriver
          ls -R chromedriver_temp
          sudo mv chromedriver_temp/chromedriver-linux64/chromedriver /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver
          rm -rf chromedriver_temp chromedriver-linux64.zip
          echo "Installed ChromeDriver version:"
          chromedriver --version

      - name: Run Discord Bot with xvfb
        env:
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          DEBUG_MODE: "False"
        run: |
          xvfb-run --auto-servernum --server-args='-screen 0 1024x768x24' python bot.py
