name: Run Discord Bot

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: "0 * * * 1-5"  # تشغيل كل ساعة من الاثنين إلى الجمعة

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Google Chrome stable (v134.0.6998.89)
        run: |
          # تحميل الحزمة بالإصدار المطلوب
          wget https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_134.0.6998.89-1_amd64.deb
          sudo dpkg -i google-chrome-stable_134.0.6998.89-1_amd64.deb || sudo apt-get -f install -y
          google-chrome --version

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install discord.py requests beautifulsoup4 selenium chromedriver_autoinstaller

      - name: Run Discord Bot with xvfb (if needed)
        env:
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          DEBUG_MODE: "False"
        run: |
          xvfb-run --auto-servernum --server-args='-screen 0 1024x768x24' python bot.py
