name: Run Discord Bot

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: "0 * * * 1-5"  # تشغيل كل ساعة في أيام الاثنين إلى الجمعة

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install discord.py requests beautifulsoup4 selenium chromedriver_autoinstaller undetected-chromedriver

      - name: Run Discord Bot with xvfb (if needed)
        env:
          TOKEN: ${{ secrets.TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          DEBUG_MODE: "False"
        run: |
          # تشغيل السكربت مع xvfb-run لضمان عمل Chrome في بيئة headless
          xvfb-run --auto-servernum --server-args='-screen 0 1024x768x24' python Bot.py
