name: Hourly News Scheduler

on:
  schedule:
    - cron: "0 * * * 1-5"  # مثال تشغيل كل ساعة من الاثنين إلى الجمعة
  workflow_dispatch:

jobs:
  run-scheduler:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Bot Script
        # هنا نمرر التوكن كمتغير بيئة
        env:
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
        run: python bot.py
